[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "piranha"
authors = [{name = "Ãine O'Toole", email = "aine.otoole@ed.ac.uk"}]
dynamic = ["version", "description"]
